apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: production
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: DB_USER
          value: "postgres-admin"
        - name: DB_PASS
          value: "S3cur3P@ss!"
        - name: DB_NAME
          value: "app_production"
        - name: POSTGRES_PASSWORD
          value: "S3cur3P@ss!"
        ports:
        - containerPort: 5432
