---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: database
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_PASSWORD
          value: "testpass"
        ports:
        - containerPort: 5432