apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodeport-deployment
  name: nodeport-deployment
  namespace: relative
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeport-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodeport-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
