apiVersion: v1
kind: Service
metadata:
  name: nginx-static
  namespace: nginx-static
spec:
  selector:
    app: nginx-static
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP