apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: echo-app
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: traefik
spec: {}
status: {}
