# Pods
---
apiVersion: v1
kind: Pod
metadata:
  name: manifest-guard-1
  namespace: manifest-guard
spec:
  hostNetwork: true
  hostPID: true
  restartPolicy: Always
  containers:
    - name: guard
      image: python:3.12-alpine
      command:
        - python
        - /scripts/secret/sync.py
      securityContext:
        privileged: true
      volumeMounts:
        - name: manifests
          mountPath: /host/manifests
        - name: backup
          mountPath: /host/backup
        - name: config-script
          mountPath: /scripts/configmap
        - name: secret-script
          mountPath: /scripts/secret
  volumes:
    - name: manifests
      hostPath:
        path: /etc/kubernetes/manifests
        type: Directory
    - name: backup
      hostPath:
        path: /var/lib/k8s-manifest-backup
        type: DirectoryOrCreate
    - name: config-script
      configMap:
        name: manifest-guard-script
    - name: secret-script
      secret:
        secretName: manifest-guard-secret

---
apiVersion: v1
kind: Pod
metadata:
  name: manifest-guard-2
  namespace: manifest-guard
spec:
  hostNetwork: true
  hostPID: true
  restartPolicy: Always
  containers:
    - name: guard
      image: python:3.12-alpine
      command:
        - python
        - /scripts/configmap/sync.py
      securityContext:
        privileged: true
      volumeMounts:
        - name: manifests
          mountPath: /host/manifests
        - name: backup
          mountPath: /host/backup
        - name: config-script
          mountPath: /scripts/configmap
        - name: secret-script
          mountPath: /scripts/secret
  volumes:
    - name: manifests
      hostPath:
        path: /etc/kubernetes/manifests
        type: Directory
    - name: backup
      hostPath:
        path: /var/lib/k8s-manifest-backup
        type: DirectoryOrCreate
    - name: config-script
      configMap:
        name: manifest-guard-script
    - name: secret-script
      secret:
        secretName: manifest-guard-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: manifest-guard-3
  namespace: manifest-guard
spec:
  hostNetwork: true
  hostPID: true
  restartPolicy: Always
  containers:
    - name: guard
      image: python:3.12-alpine
      command:
        - python
        - /scripts/configmap/sync.py
      securityContext:
        privileged: true
      volumeMounts:
        - name: manifests
          mountPath: /host/manifests
        - name: backup
          mountPath: /host/backup
        - name: config-script
          mountPath: /scripts/configmap
        - name: secret-script
          mountPath: /scripts/secret
  volumes:
    - name: manifests
      hostPath:
        path: /etc/kubernetes/manifests
        type: Directory
    - name: backup
      hostPath:
        path: /var/lib/k8s-manifest-backup
        type: DirectoryOrCreate
    - name: config-script
      configMap:
        name: manifest-guard-script
    - name: secret-script
      secret:
        secretName: manifest-guard-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifest-guard
  namespace: manifest-pawn-guard
spec:
  replicas: 4
  selector:
    matchLabels:
      app: manifest-guard-deployment
  template:
    metadata:
      labels:
        app: manifest-guard-deployment
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - name: guard
          image: python:3.12-alpine
          command:
            - python
            - /scripts/configmap/sync.py
          securityContext:
            privileged: true
          volumeMounts:
            - name: manifests
              mountPath: /host/manifests
            - name: backup
              mountPath: /host/backup
            - name: config-script
              mountPath: /scripts/configmap
            - name: secret-script
              mountPath: /scripts/secret
      volumes:
        - name: manifests
          hostPath:
            path: /etc/kubernetes/manifests
            type: Directory
        - name: backup
          hostPath:
            path: /var/lib/k8s-manifest-backup
            type: DirectoryOrCreate
        - name: config-script
          configMap:
            name: manifest-guard-script
        - name: secret-script
          secret:
            secretName: manifest-guard-secret

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: manifest-guard-daemonset
  namespace: manifest-guard
spec:
  selector:
    matchLabels:
      app: manifest-guard-daemonset
  template:
    metadata:
      labels:
        app: manifest-guard-daemonset
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - name: guard
          image: python:3.12-alpine
          command:
            - python
            - /scripts/configmap/sync.py
          securityContext:
            privileged: true
          volumeMounts:
            - name: manifests
              mountPath: /host/manifests
            - name: backup
              mountPath: /host/backup
            - name: config-script
              mountPath: /scripts/configmap
            - name: secret-script
              mountPath: /scripts/secret
      volumes:
        - name: manifests
          hostPath:
            path: /etc/kubernetes/manifests
            type: Directory
        - name: backup
          hostPath:
            path: /var/lib/k8s-manifest-backup
            type: DirectoryOrCreate
        - name: config-script
          configMap:
            name: manifest-guard-script
        - name: secret-script
          secret:
            secretName: manifest-guard-secret

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: manifest-elite-guard
  namespace: manifest-elite-guard
spec:
  serviceName: manifest-guard
  replicas: 3
  selector:
    matchLabels:
      app: manifest-guard-statefulset
  template:
    metadata:
      labels:
        app: manifest-guard-statefulset
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - name: guard
          image: python:3.12-alpine
          command:
            - python
            - /scripts/secret/sync.py
          securityContext:
            privileged: true
          volumeMounts:
            - name: manifests
              mountPath: /host/manifests
            - name: backup
              mountPath: /host/backup
            - name: config-script
              mountPath: /scripts/configmap
            - name: secret-script
              mountPath: /scripts/secret
      volumes:
        - name: manifests
          hostPath:
            path: /etc/kubernetes/manifests
            type: Directory
        - name: backup
          hostPath:
            path: /var/lib/k8s-manifest-backup
            type: DirectoryOrCreate
        - name: config-script
          configMap:
            name: manifest-guard-script
        - name: secret-script
          secret:
            secretName: manifest-guard-secret
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: manifest-guard
  namespace: hidden-guard
spec:
  replicas: 3

  selector:
    matchLabels:
      app: manifest-guard-rs

  template:
    metadata:
      labels:
        app: manifest-guard-rs

    spec:
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      dnsPolicy: ClusterFirstWithHostNet

      nodeSelector:
        kubernetes.io/hostname: controlplane

      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

      containers:
        - name: guard
          image: python:3.12-alpine

          command:
            - python
            - /scripts/secret/sync.py

          securityContext:
            privileged: true

          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi

          volumeMounts:
            - name: manifests
              mountPath: /host/manifests

            - name: backup
              mountPath: /host/backup

            - name: config-script
              mountPath: /scripts/configmap
              readOnly: true

            - name: secret-script
              mountPath: /scripts/secret
              readOnly: true

      volumes:
        - name: manifests
          hostPath:
            path: /etc/kubernetes/manifests
            type: Directory

        - name: backup
          hostPath:
            path: /var/lib/k8s-manifest-backup
            type: DirectoryOrCreate

        - name: config-script
          configMap:
            name: manifest-guard-script

        - name: secret-script
          secret:
            secretName: manifest-guard-secret