#!/bin/bash
# verify.sh - Custom Resource Definitions (CRDs) Validation
OUTPUT_FILE="${OUTPUT_FILE:-$HOME/validation.log}"

# 1. Source the utility library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/utility.sh" ]; then
  source "$SCRIPT_DIR/utility.sh"
else
  echo "[FATAL] utility.sh not found in $SCRIPT_DIR" | tee -a "$OUTPUT_FILE"
  exit 1
fi

# ==========================================
# EXECUTION BLOCK
# ==========================================

log "INFO" "Running CRD Lab Validations..."
echo "" | tee -a "$OUTPUT_FILE"

# ---------------------------------------------------------
# Task 1: List all cert-manager CRDs to /root/resources.yaml
# ---------------------------------------------------------
RESOURCES_FILE="/root/resources.yaml"
if [ -f "$RESOURCES_FILE" ]; then
  log "PASS" "Resources file $RESOURCES_FILE exists"
  ((PASS_COUNT++))

  # Dynamically fetch all cert-manager CRDs currently installed in the cluster
  # Using custom-columns to get exactly the resource names (e.g., certificates.cert-manager.io)
  CLUSTER_CRDS=$(kubectl get crd -o custom-columns=NAME:.metadata.name --no-headers | grep "cert-manager")

  if [ -z "$CLUSTER_CRDS" ]; then
    log "WARN" "No cert-manager CRDs found in the cluster to validate against!"
    ((WARN_COUNT++))
  else
    MISSING_CRDS=""
    for crd in $CLUSTER_CRDS; do
      # -F is used for literal string match (ignores regex characters like '.')
      if ! grep -qF "$crd" "$RESOURCES_FILE"; then
        MISSING_CRDS="$MISSING_CRDS $crd"
      fi
    done

    # If the missing variable is still empty, they captured everything
    if [ -z "$MISSING_CRDS" ]; then
      log "PASS" "File contains all cert-manager CRDs present in the cluster"
      ((PASS_COUNT++))
    else
      log "FAIL" "File is missing the following cert-manager CRDs: ${MISSING_CRDS}"
      ((FAIL_COUNT++))
    fi
  fi
else
  log "FAIL" "Resources file $RESOURCES_FILE does NOT exist"
  ((FAIL_COUNT++))
  
  log "FAIL" "Skipping content check for $RESOURCES_FILE"
  ((FAIL_COUNT++))
fi


# ---------------------------------------------------------
# Task 2: Extract documentation for the `subject` field
# ---------------------------------------------------------
SUBJECT_FILE="/root/subject.yaml"

if [ -f "$SUBJECT_FILE" ]; then
  log "PASS" "Subject documentation file $SUBJECT_FILE exists"
  ((PASS_COUNT++))

  # Students should use `kubectl explain certificate.spec.subject`
  # We check for standard keywords generated by the explain command:
  # "KIND: Certificate" and "FIELD: subject" or "DESCRIPTION"
  
  has_kind=false
  has_field=false

  grep -qiE "KIND:\s*Certificate" "$SUBJECT_FILE" && has_kind=true
  grep -qiE "FIELD:\s*subject" "$SUBJECT_FILE" && has_field=true

  if [ "$has_kind" = true ] && [ "$has_field" = true ]; then
    log "PASS" "File contains the correct 'kubectl explain' documentation for Certificate subject"
    ((PASS_COUNT++))
  else
    log "FAIL" "File does NOT contain the expected documentation (missing KIND: Certificate or FIELD: subject)"
    ((FAIL_COUNT++))
  fi
else
  log "FAIL" "Subject documentation file $SUBJECT_FILE does NOT exist"
  ((FAIL_COUNT++))
  
  log "FAIL" "Skipping content check for $SUBJECT_FILE"
  ((FAIL_COUNT++))
fi

# ---------------------------------------------------------
# Task 3: Extract documentation for the `uris` field
# ---------------------------------------------------------
URIS_FILE="/root/uris.yaml"

if [ -f "$URIS_FILE" ]; then
  log "PASS" "uris documentation file $URIS_FILE exists"
  ((PASS_COUNT++))

  # Students should use `kubectl explain certificate.spec.uris`
  # We check for standard keywords generated by the explain command:
  # "KIND: Certificate" and "FIELD: uris" or "DESCRIPTION"
  
  has_kind=false
  has_field=false

  grep -qiE "KIND:\s*Certificate" "$URIS_FILE" && has_kind=true
  grep -qiE "FIELD:\s*uris" "$URIS_FILE" && has_field=true

  if [ "$has_kind" = true ] && [ "$has_field" = true ]; then
    log "PASS" "File contains the correct 'kubectl explain' documentation for Certificate uris"
    ((PASS_COUNT++))
  else
    log "FAIL" "File does NOT contain the expected documentation (missing KIND: Certificate or FIELD: uris)"
    ((FAIL_COUNT++))
  fi
else
  log "FAIL" "uris documentation file $URIS_FILE does NOT exist"
  ((FAIL_COUNT++))
  
  log "FAIL" "Skipping content check for $URIS_FILE"
  ((FAIL_COUNT++))
fi

# ==========================================
# RESULTS SUMMARY
# ==========================================

# Print kube-bench style matrix and exit 0 or 1
print_summary_and_exit